version: '3'
services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
